project:
  type: book

book:
  title: "Reader Week 1"
  author: "Maurice Koster"
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Sequences"
      chapters:
        - sequences/01-intro.qmd
        - sequences/02-convergence-R.qmd
        - sequences/03-monotone.qmd
        - sequences/04-continuity.qmd
        - sequences/05-Rm.qmd
    - part: "Series"
      chapters:
        - series/01-intro.qmd
        - series/02-basic-properties.qmd
        - series/03-alternating.qmd
        - series/04-absolute.qmd
        - series/05-ratio-power.qmd
    - part: "Taylor polynomials"
      chapters:
        - taylor/01-intro.qmd
        - taylor/02-tangency-taylor-polynomials.qmd
        - taylor/03-taylor-theorem.qmd
        - taylor/04-applications.qmd
        - taylor/05-taylor-series.qmd

format:
  html:
    include-after-body: _includes/footer.html
    css: css/styles.css
    toc: true
    number-sections: true
    number-depth: 1 
    theme: cosmo

execute:
  echo: true
  warning: false
  message: false
  cache: false
  jupyter: python3
